/**
 * ControllerKenya.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package co.ke.transunion.crbws.ws;

public interface ControllerKenya extends java.rmi.Remote {
    public Product150 getProduct150(String username, String password, String code, String infinityCode, String companyName, String companyRegNo, String taxID, String vatID, java.util.Calendar companyRegDate, String postalBoxNo, String postalTown, String postalCountry, String telephoneNo, String faxNo, String websiteAddress, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product151 getProduct151(String username, String password, String code, String infinityCode, String companyName, String companyRegNo, String taxID, String vatID, java.util.Calendar companyRegDate, String postalBoxNo, String postalTown, String postalCountry, String telephoneNo, String faxNo, String websiteAddress, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product152 getProduct152(String username, String password, String code, String infinityCode, String companyName, String companyRegNo, String taxID, String vatID, java.util.Calendar companyRegDate, String postalBoxNo, String postalTown, String postalCountry, String telephoneNo, String faxNo, String websiteAddress, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product153 getProduct153(String username, String password, String code, String infinityCode, String companyName, String companyRegNo, String taxID, String vatID, java.util.Calendar companyRegDate, String postalBoxNo, String postalTown, String postalCountry, String telephoneNo, String faxNo, String websiteAddress, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public CreditBal getCreditBal(String username, String password, String code, String infinityCode) throws java.rmi.RemoteException;
    public Product100 getProduct100(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product126 getProduct126(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product401 getProduct401(String username, String password, String code, String infinityCode, String phoneNumber, int reportSector, int reportReason, String message) throws java.rmi.RemoteException;
    public Product402 getProduct402(String username, String password, String code, String infinityCode, String documentNumber, String names, String phoneNumber, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product403 getProduct403(String username, String password, String code, String infinityCode, String phoneNumber, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product405 getProduct405(String username, String password, String code, String infinityCode, String origin, String dest, String receivedTimeStamp, String transactionDate, String transactionTime, String transactionCode, String transactionMobileNo, String transactionAccount, String senderNames, String transactionAmount) throws java.rmi.RemoteException;
    public Product406 getProduct406(String username, String password, String code, String infinityCode, String phoneNumber, String emailAddress, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product159 getProduct159(String username, String password, String code, String infinityCode, String companyName, String companyRegNo, String taxID, String vatID, java.util.Calendar companyRegDate, String postalBoxNo, String postalTown, String postalCountry, String telephoneNo, String faxNo, String websiteAddress, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product125 getProduct125(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product108 getProduct108(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product112 getProduct112(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product114 getProduct114(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product110 getProduct110(String username, String password, String code, String infinityCode, int crn, String phoneNumber, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product121 getProduct121(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportReason) throws java.rmi.RemoteException;
    public Product124 getProduct124(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product102 getProduct102(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportReason) throws java.rmi.RemoteException;
    public Product101 getProduct101(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product104 getProduct104(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product116 getProduct116(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product118 getProduct118(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product105 getProduct105(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product109 getProduct109(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product103 getProduct103(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportReason) throws java.rmi.RemoteException;
    public Product107 getProduct107(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product115 getProduct115(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public Product122 getProduct122(String username, String password, String code, String infinityCode, String name1, String name2, String name3, String name4, String nationalID, String passportNo, String serviceID, String alienID, String taxID, java.util.Calendar dateOfBirth, String postalBoxNo, String postalTown, String postalCountry, String telephoneWork, String telephoneHome, String telephoneMobile, String physicalAddress, String physicalTown, String physicalCountry, int reportSector, int reportReason) throws java.rmi.RemoteException;
    public ServerInfo getServerInfo(String username, String password, String code, String infinityCode) throws java.rmi.RemoteException;
}
